### ISSUE TITLE
Crashing at kotlinx.coroutines.DefaultExecutor

### ISSUE THREAD

**Issue by nirukk52** [dgngulcan/droid-feed#30]
App is constantly crashing at

Whenever I am scrolling it is crashing.

2018-12-03 00:40:44.815 24537-24582/com.hiphop W/OkHttpClient: A connection to https://settings.crashlytics.com/ was leaked. Did you forget to close a response body?

2018-12-03 00:40:44.822 24537-24627/com.hiphop E/AndroidRuntime: FATAL EXCEPTION: kotlinx.coroutines.DefaultExecutor
    Process: com.hiphop, PID: 24537
    kotlin.KotlinNullPointerException
        at kotlinx.coroutines.experimental.internal.ThreadSafeHeap.removeAtImpl(ThreadSafeHeap.kt:97)
        at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:385)
        at kotlinx.coroutines.experimental.DefaultExecutor.run(DefaultExecutor.kt:61)
        at java.lang.Thread.run(Thread.java:764)

**Comment by dgngulcan** [comment]
Is this the full log of the crash? It is hard to tell what is going on from the logs. 
I could not reproduce the crash, however, I highly suspect it may be happening in the adapter where a nullable object is asserted by `!!` or a nullable value is defined as not-null.

If you could share more information, please do.

**Comment by nirukk52** [comment]
> Is this the full log of the crash? It is hard to tell what is going on from the logs.
> I could not reproduce the crash, however, I highly suspect it may be happening in the adapter where a nullable object is asserted by `!!` or a nullable value is defined as not-null.
> 
> If you could share more information, please do.

**Comment by nirukk52** [comment]
> Is this the full log of the crash? It is hard to tell what is going on from the logs.
> I could not reproduce the crash, however, I highly suspect it may be happening in the adapter where a nullable object is asserted by `!!` or a nullable value is defined as not-null.
> 
> If you could share more information, please do.

**Comment by nirukk52** [comment]
It is crashing once in five times. Sometimes once in 10 times.
I am not able to retrieve any further information.
It is not related to the null object in adapter if that was the case it would've always crashed.
And the thing is it is not happening in when i am downloading from Playstore. But is crashing in dev and master.
Can you tell me the commit number at which you made the release build for play store.?

**Comment by dgngulcan** [comment]
The `master` branch is the codebase that the Play store version is exported from. Tested on a new project, it is not crashing.

> It is not related to the null object in adapter if that was the case it would've always crashed.

The news feed is aggregated from different RSS feeds. Sometimes some values may be missing for some items.

Try debugging the adapter that you are displaying the feed with.

**Comment by nirukk52** [comment]
I tried updating to `'kotlin_coroutines': '1.0.1'` from `'kotlin_coroutines': '0.30.0'` which gave `circular dependecy in FeedViewModel` error.
Then I reverted to `'kotlin_coroutines': '0.26.0'`, it is not crashing since then. I think you have updated the dependencies after playstore build.
It is fixed for now. Thanks for the prompt response.
